FROM mashmb/nvim-go:dev
RUN apt-get update && \
	apt-get install -y bash-completion tmux openssh-client locales
RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
	locale-gen && update-locale
RUN mkdir -p github/shin-imai && cd github/shin-imai && \
  git clone https://github.com/shin-imai/dotfiles.git && cd dotfiles && \
	./install_tools.sh && cp -rp .bash* .kuberc .tmux.conf.local /root
RUN apt-get clean && rm -f /root/.bash_history
